### ISSUE TITLE
KeyError: 'addedBy'

### ISSUE THREAD

**Issue by nikat** [dasshit/async-icq#1]
Traceback (most recent call last):
  File "/app/myteam.py", line 97, in <module>
    kotanbot.bot.start_poll()
  File "/usr/local/lib/python3.9/site-packages/async_icq/bot.py", line 1065, in start_poll
    self.loop.run_until_complete(self.start_polling())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/async_icq/bot.py", line 998, in start_polling
    events = [
  File "/usr/local/lib/python3.9/site-packages/async_icq/bot.py", line 999, in <listcomp>
    Event(
  File "/usr/local/lib/python3.9/site-packages/async_icq/events.py", line 89, in __init__
    self.addedBy = UserInfo(**data['addedBy'])
KeyError: 'addedBy'

**Comment by nikat** [comment]
бот падает, когда любой пользователь входит по ссылке в группу
